# Generated by Django 2.0.3 on 2018-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='iconourl',
            field=models.CharField(default='http://cdn5.dibujos.net/dibujos/pintados/201227/coche-americano-vehiculos-coches-pintado-por-fernandogh-9751138.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
